const dataList = {
    departamentos: [
        'Call Center',
        'Call Center Sala de Ventas Cazzar',
        'Call Center Costa La Gloria',
        'Call Center Costa 1',
        'Call Center Costa 1A',
        'Call Center Costa 2',
        'Call Center Costa 3',
        'Call Center Ensenada',
        'Call Center Costa 1 Puerto Nuevo',
        'Unidad de Venta',
        'Ventas',
        'Cobranza',
    ],
    coords: [
        "Carlos Lenin",
        "Coord. Claudia Noriega",
        "Coord. Gabriela Cano",
        "Coord. Edgar Trejo",
        "Coord. Mariana Fragoso",
        "Aux. Yulissa Orozco",
        "Aux. Adolfo Martinez",
        "Aux. Alejandro Cazorla",
        "Aux. Ashram Mendez",
        "Aux. Bernardo Tovar",
        "Aux. Ezequiel Espinoza",
        "Aux. Ana Lizeth Lopez",
        "Aux. Kristina Voronina",
        "Aux. Alejandra Garcia",
        "Aux. Damaris Lopez",
        "Aux. Jared Mendez",
        "Aux. Jesus Villegas",
        "Aux. Isabel Aguilar",
        "Aux. Sabrina Martinez",
        "Aux. Gabriel Hidalgo",
        "Aux. Arturo Ubiedo",
        "Aux. Nayeli Juarez",
        "Aux. Vanessa Parra",
        "Aux. Veronica Gonzalez",
        "Aux. Victoria Martin",
        "Aux. Jesica Garcia",
        "Coord. Carlos Merlo",
        "Evaristo Lizarraga",
        "Diana Hernandez",
        "Elizabeth Portillo",
        "Coord. Gabriela Solano",
        "Elizabeth Portillo y/o Gabriela Solano",
        "Elizabeth Portillo y/o Ana Lizeth Lopez",
        "Elizabeth Portillo y/o Carlos Maldonado",
        "Coordinador Prueba",
        "Coord. Fernanda Peralta",
    ],
    fuentesCliente:[
        "Aviso",
        "Llamada no solicitada",
        "Recomendación de empleado",
        "Recomendación externa",
        "Tienda en línea",
        "Socio",
        "Facebook",
        "Twitter",
        "Relaciones públicas",
        "Alias del correo electrónico de ventas",
        "Google+",
        "Socio de seminarios",
        "Seminario interno",
        "Exposición comercial",
        "Descargar web",
        "Investigación web",
        "Casos de la Web",
        "Correo web",
        "Chat",
        "Infomercial",
        "Página Web",
        "Carteleras",
        "Periodico",
        "Radio",
        "Volanteo",
        "Oficinas",
        "Referido Inverplus",
        "Recomendados",
        "Flyers",
        "Camion",
        "Google AdWords",
        "BAJA 500 2022",
        "CARRERA ROSARITO ABRIL 2022",
        "CARRETA PLAZA LAS AMERICAS",
        "CARTELERA SENTRI",
        "CONTENEDOR ALAMAR 3",
        "DESARROLLO LOS OLIVOS",
        "DESARROLLO RANCHO ESCONDIDO",
        "ENTREVISTA INVASORA USA",
        "EVENTO LIBERTEX 2022",
        "EXPO BODA 2022",
        "FACEBOOK CAMPESTRE VALLECITOS",
        "FACEBOOK CIELO",
        "FACEBOOK ENCINO SOLO",
        "FACEBOOK MISION DE GUADALUPE",
        "FACEBOOK RANCHETTES",
        "FACEBOOK RANCHO LAS PUERTAS",
        "FACEBOOK RESIDENCIAL LOS OLIVOS",
        "FACEBOOK VISTA DE PUERTO NUEVO",
        "GIGANTOGRAFIA COSTA DORADA",
        "GRUPO CADENA",
        "LANDING PAGE CIELO",
        "LANDING PAGE COSTA DORADA",
        "LANDING PAGE SAHARA",
        "LANDING PAGE TERRENOS CAMPESTRES",
        "OFICINA LAS AMERICAS",
        "PANTALLA ALAMEDA",
        "PASE CALL CENTER LA GLORIA",
        "PISTA DE HIELO 2021",
        "PROSPECCION AMBULANTE ROSARITO",
        "ZONKEYS 2022",
        "CAMION TOSCANA",
        "CARTELERA AGUAJE DE LA TUNA",
        "CARTELERA ALAMAR",
        "CARTELERA ALAMAR 2",
        "CARTELERA ALAMAR 3",
        "CARTELERA AVENIDA INTERNACIONAL",
        "CARTELERA CARRETERA ROSARITO ENSENADA",
        "CARTELERA CAZZAR",
        "CARTELERA CENTRO CIVICO ROSARITO",
        "CARTELERA CENTRO HISTORICO TKT",
        "CARTELERA CHARLYS",
        "CARTELERA CIELO",
        "CARTELERA CORPORATIVO DEL PRADO",
        "CARTELERA COSTA DORADA 1",
        "CARTELERA COSTA DORADA 3",
        "CARTELERA COSTA DORADA 4",
        "CARTELERA COSTA DORADA 5",
        "CARTELERA CRISTO POR CALAFIA",
        "CARTELERA CUAUHTEMOC",
        "CARTELERA CUCAPAH",
        "CARTELERA CUOTA 1 COSTA DORADA",
        "CARTELERA CUOTA ROS-ENS VILLA TOSCANA",
        "CARTELERA CUOTA TKT",
        "CARTELERA DOBLE ESCÉNICA",
        "CARTELERA EL CHAPARRAL",
        "CARTELERA EL CHAPARRAL 2",
        "CARTELERA ENTRADA A PLAYAS",
        "CARTELERA ENTRADA PLAYAS",
        "CARTELERA ESCENICA PLAYAS-ROS",
        "CARTELERA ESCENICA ROSARITO ENS",
        "CARTELERA GARITA CHAPARRAL",
        "CARTELERA GARITA DE OTAY 1",
        "CARTELERA GARITA DE OTAY 2",
        "CARTELERA INTERNACIONAL 2",
        "CARTELERA LAGUNA SALADA",
        "CARTELERA LIBRE ESCENICA ENSENADA",
        "CARTELERA LIBRE ROSARITO 1",
        "CARTELERA LIBRE ROSARITO 2",
        "CARTELERA LIBRE ROSARITO 3",
        "CARTELERA LINEA 3",
        "CARTELERA LINEA CIELO 1",
        "CARTELERA MUJER INVERPLUS",
        "CARTELERA NODO OTAY",
        "CARTELERA PABELLON ROSARITO",
        "CARTELERA PANAMERICANO",
        "CARTELERA PLAZA GALERIAS",
        "CARTELERA PLAZA INFINITI",
        "CARTELERA PRIMOTAPIA-ARENALES",
        "CARTELERA PUENTE REAL INN",
        "CARTELERA READY LANE",
        "CARTELERA READY LANE 2",
        "CARTELERA READY LANE 5",
        "CARTELERA REAL DE SANTA FE",
        "CARTELERA SAHARA",
        "CARTELERA SAN PEDRO",
        "CARTELERA SIMSA",
        "CARTELERA SUBIDA AEROPUERTO",
        "CARTELERA TERAN TERAN MEXICALI",
        "CARTELERA UBICACIÓN VILLA TOSCANA",
        "CARTELERA UNIPOLAR CHICO ROSARITO",
        "CARTELERA UNIPOLAR CUOTA PLAYAS DE TIJ- RTO",
        "CARTELERA UNIPOLAR ENTRADA TIJ",
        "CARTELERA VISTAS DEL RIO 1",
        "CASA DE PIEDRA",
        "CASETA MISIÓN GUADALUPE",
        "CHAT FB",
        "CIELO OFICINAS",
        "CIELO RESIDENCIAL VALLAS",
        "CONTENEDOR 1 PASEO LAS BRISAS",
        "CONTENEDOR 2 PASEO LAS BRISAS",
        "CONTENEDOR ALAMAR",
        "CONTENEDOR BETHEL",
        "CONTENEDOR CANTAMAR",
        "CONTENEDOR CASA DE PIEDRA",
        "CONTENEDOR CIELO 2",
        "CONTENEDOR COSTA DORADA 1",
        "CONTENEDOR COSTA DORADA 3",
        "CONTENEDOR LA FONDA",
        "CONTENEDOR LA PALOMA",
        "CONTENEDOR LOMAS DEL VALLE",
        "CONTENEDOR MISIÓN GUADALUPE",
        "CONTENEDOR PARAISO LADRILLERA",
        "CONTENEDOR POPOTLA",
        "CONTENEDOR PUERTO NUEVO",
        "CONTENEDOR RANCHO LA PUERTA",
        "CONTENEDOR REAL DE SANTA FE",
        "CONTENEDOR REAL DE SANTA FE 1",
        "CONTENEDOR SAHARA",
        "CONTENEDOR SAHARA 2",
        "CONTENEDOR SANTA FE LA PAJARITA",
        "CONTENEDOR SANTA FE TOOGINOS",
        "CONTENEDOR SEVEN ELEVEN",
        "CONTENEDOR TARAY",
        "CONTENEDOR TERAN TERAN",
        "CONTENEDOR VALLE DE GUADALUPE",
        "CONTENEDOR VALLE DEL CIMARRON 1",
        "CONTENEDOR VALLE DEL CIMARRON 2",
        "CONTROL REMOTO LA INVASORA 94.5",
        "CONTROL REMOTO PULSAR",
        "DESARROLLO VISTAS DEL RIO",
        "DESAYUNOS MUJER INVERPLUS",
        "EL SHOW DE MARIO ALBERTO",
        "EL TRIANGULO VALLE DE GUADALUPE",
        "EMPODERATE LA",
        "ENCUESTAS",
        "ENCUESTAS CALLE TIJUANA",
        "ENCUESTAS LINEA OTAY",
        "ENCUESTAS MEXICALI",
        "ENCUESTAS SAN YSIDRO",
        "ENSENADA VILLA MARINA",
        "ENTREVISTA GUSTAVO VARGAS",
        "ENTREVISTA TV AZTECA",
        "ENTREVISTAS RADIO LOS ANGELES",
        "ENTREVISTAS TELEVISA",
        "ENVIOS MASIVOS",
        "EVENTO FATO",
        "EVENTO SENIOR EXPO ONTARIO CA",
        "EXA FM",
        "EXPO ARTE Y DECO ROSARITO 2019",
        "EXPO BODA 2020",
        "EXPO MUEBLE",
        "EXPO MUEBLE 2022",
        "FACEBOOK AGENTES",
        "FACEBOOK ALAMAR",
        "FACEBOOK ALFREDO ALVAREZ",
        "FACEBOOK BETHEL",
        "FACEBOOK COSTA DORADA",
        "FACEBOOK EMPRESA",
        "FACEBOOK GRUPO CONCORDIA USA",
        "FACEBOOK SAHARA",
        "FACEBOOK TARAY",
        "FACEBOOK VILLA PARAISO",
        "FACEBOOK VILLATOSCANA",
        "FACEBOOK VISTAS DEL RIO",
        "FACEBOOK USA",
        "FB AGENTE 1",
        "FB AGENTE 10",
        "FB AGENTE 11",
        "FB AGENTE 12",
        "FB AGENTE 13",
        "FB AGENTE 14",
        "FB AGENTE 15",
        "FB AGENTE 16",
        "FB AGENTE 17",
        "FB AGENTE 18",
        "FB AGENTE 19",
        "FB AGENTE 2",
        "FB AGENTE 20",
        "FB AGENTE 21",
        "FB AGENTE 22",
        "FB AGENTE 23",
        "FB AGENTE 24",
        "FB AGENTE 25",
        "FB AGENTE 26",
        "FB AGENTE 27",
        "FB AGENTE 28",
        "FB AGENTE 3",
        "FB AGENTE 4",
        "FB AGENTE 5",
        "FB AGENTE 6",
        "FB AGENTE 7",
        "FB AGENTE 8",
        "FB AGENTE 9",
        "FLYERS TABLOIDES TOSCANA",
        "FLYERS / TABLOIDES CIELO",
        "FLYERS / TABLOIDES VILLA GLORIA",
        "FLYERS LINEA",
        "FLYERS LOS ANGELES",
        "GIGANTOGRAFIA SENTRI",
        "HOSPITAL ÁNGELES",
        "INFOMERCIAL LA",
        "INFOMERCIAL AZTECA LA",
        "INFOMERCIAL CANAL 22",
        "INFOMERCIAL ESTRELLA TV",
        "INFOMERCIAL TELEMUNDO LOS ANGELES",
        "INFOMERCIAL TELEMUNDO SAN DIEGO",
        "INFOMERCIAL TELEVISA GUADALAJARA",
        "INFOMERCIAL TELEVISA MEXICALI",
        "INFOMERCIAL TELEVISA MONTERREY",
        "INFOMERCIAL TELEVISA TIJUANA",
        "INFOMERCIAL TV AZTECA",
        "INFOMERCIAL UNIVISION LA",
        "INSTAGRAM USA",
        "LA BUENA EL MALO Y EL FEO",
        "LA MEJOR 90.7",
        "LA OPINION",
        "LA PUERTA",
        "LA QUE BUENA LA",
        "LA QUE BUENA SD",
        "LA RAZA LA",
        "LA TIMES",
        "LINEA 1",
        "LINEA 2",
        "LINEA 4",
        "LLAMADA EN FRIO",
        "LOS ANGELES MIXER 2019",
        "LOS PANCHOS",
        "MARQUESINA SENTRI",
        "Memorial Day Facebook",
        "MENCIÓN LA RANCHERA",
        "MERCADO DE ABASTOS",
        "MODULO CARRITO LAS AMERICAS",
        "MUJER INVERPLUS",
        "MURO PLAZA CALIFORNIA",
        "NOCHES DE INVERSIÓN CAZZAR",
        "OFICINA ALAMAR",
        "OFICINA ALTIPLANO",
        "OFICINA BETHEL",
        "OFICINA CAZZAR",
        "OFICINA LOS ANGELES",
        "OFICINA PLAYAS",
        "OFICINA PUERTO NUEVO",
        "OFICINA SENDEROS ROSARITO",
        "OFICINAS LINEA",
        "PAGINA WEB CIELO",
        "PAGINA WEB GRUPO CONCORDIA",
        "PAGINA WEB TECATE",
        "PAGINA WEB TOSCANA",
        "PANTALLA CESPT",
        "PANTALLA CHAPARRAL",
        "PANTALLA HOTEL CORONA",
        "PANTALLA OTAY",
        "PANTALLA PLAZA FIESTA",
        "PANTALLA REAL INN",
        "PANTALLA TV AZTECA",
        "PERIODICO FRONTERA",
        "PLAN DE RECOMPENSA",
        "PONOSA VALLAS CIELO",
        "PONOSA VALLAS PARAÍSO",
        "PROGRAMACION NBC",
        "PROGRAMACION VIX",
        "PROMOCIÓN 40",
        "PROMOTORES VIRTUALES",
        "PROSPECTADORES GARITA",
        "PUENTE BUENA VISTA",
        "PUENTE PLAYAS",
        "PUERTO NUEVO",
        "PUNTO DE VENTA ALAMAR",
        "PUNTO DE VENTA BELLA VISTA",
        "PUNTO DE VENTA BRISAS",
        "PUNTO DE VENTA CASA KEPLER",
        "PUNTO DE VENTA CIMARRÓN",
        "PUNTO DE VENTA LA GLORIA",
        "PUNTO DE VENTA MERCADO HIDALGO",
        "PUNTO DE VENTA PONOSA",
        "RADIO GUSTAVO VARGAS",
        "RADIO LATINA",
        "READY LANE 3",
        "READY LANE 4",
        "REPORTE DE GARITAS",
        "SABOR A VALLE 28",
        "SABOR A VALLE 29",
        "SENTRI",
        "SPOT CNR",
        "SPOT TELEVISA",
        "SPOT TELEVISA 6:00 PM",
        "SPOT TELEVISA 8:00 PM",
        "SPOT TV AZTECA",
        "SPOT TV AZTECA 10:00 AM",
        "SPOT TV AZTECA 8:30 PM",
        "SUCCESSFUL AGING EXPO 2019",
        "TAMALE FESTIVAL",
        "TECATE LOS ENCINOS",
        "TECATE PFC",
        "TELEVISA TIJUANA",
        "TORNEO DE GOLF CAMPESTRE 2022",
        "TORNEO DE GOLF REAL DEL MAR 2019",
        "TOURS",
        "TV AZTECA SAN DIEGO",
        "UNIDAD DE VENTA",
        "UNIRADIO",
        "UNIRADIO PULSAR",
        "VALLA MOVIL ELEVADA",
        "VALLAS MISIÓN DE GUADALUPE",
        "VALLAS SEVEN ELEVEN",
        "VILLA GLORIA",
        "VILLA GLORIA OFICINAS",
        "VILLA TOSCANA OFICINAS",
        "VIVANUNCIOS",
        "VOLANTE BAJA REAL STATE TOUR",
        "VOLANTE VENTAS",
        "VOLANTES MISION",
        "WEB GPO CONCORDIA USA",
        "WEB MÓVIL SYS",
        "CONTROL EXA 91.7",
        "CARTELERA LA24-10",
        "CARTELERA LA48-12",
        "CARTELERA LA48D-007",
        "CARTELERA LA48D-006",
        "CARTELERA LA48D-005",
        "CARTELERA LA48D-013",
        "CARTELERA LA48D-004",
        "CARTELERA LA48-015",
        "CARTELERA LA48D-008",
        "CARTELERA LA48D-011",
        "CARTELERA LA48D-003",
        "WEB VIVE LA BAJA",
        "CONTROL EXA ENSENADA",
        "FERIA DEL MAR 2022",
        "ACTIVACION PLAZA ALAMEDA",
    ],
    sucursales: [
        'Oficina Cazzar',
        'Oficina Altiplano',
        'Oficina Alamar',
        'Oficina Sainz',
        'Oficina Lomas del Valle',
        'Costa Dorada',
        'Oficina Seven Eleven',
        'Oficina Cielo',
        'Oficina Villa Toscana',
        'Oficina La Gloria',
        'Oficina Sendero',
        'Oficina La Puerta',
        'Oficina Santa Ana',
        'Oficina Los Angeles',
        'Oficina San Ysidro',
        'Oficina Ensenada',
        'Oficina Puerto Nuevo',
    ],
    zonas: [
        "Costa",
        "Costa 1",
        "Costa 2",
        "Costa 3",
        "Costa 4",
        "Costa 5",
        "Oriente",
        "Oficina Centro",
        "Oficina Los Angeles",
        "Oficina Tijuana 2",
        "Oficina Revolucion",
        "Sala de Ventas Cazzar",
    ],
    venta: [
        "Call Center",
        "Call Center Ensenada",
        "Call Center Sala de Ventas Cazzar",
        "Call Center Costa La Gloria",
        "Call Center Costa 1",
        "Call Center Costa 1 A",
        "Call Center Costa 2",
        "Call Center Costa 3",
        "Call Center Costa 5",
        "Call Center Puerto Nuevo",
        "Call Center Unidad de Venta",
    ],
    operador: [
        "ALLISON VALERIA RODRIGUEZ AVILA",
        "ARANZA RIBERA",
        "ARELY DE LA ROSA",
        "AZAEL ESTRELLA",
        "BAYRON REYES",
        "BRENDA SEGURA",
        "BRYAN RODRIGUEZ",
        "CARLOS ALBETTO GONZALEZ GONZALEZ",
        "CRISTAL GONZALEZ",
        "DANIEL JIMENEZ",
        "EZEQUIEL ALEJANDRO MORENO DOMINGUEZ",
        "FERNANDA CECILIA HERNÁNDEZ BEIKA",
        "ITZEL GALAN",
        "JESUS EDUARDO HERRERA VALENZUELA",
        "KARINA TLAZOLA",
        "MARGARITA PEREZ",
        "MELINA GRISELDA SALDAÑA PEREZ",
        "NANCY LILIANA RODRIGUEZ MUÑOZ",
        "OLGA GRAJEDA",
        "RAQUEL VELEZ",
        "SAHID GOMEZ",
        "SAM CAMPOS",
        "VICENTE RODRIGUEZ",
        "WENDOLINE RODIGUEZ",
        "YANELY LÓPEZ",
        "YARELI PARRA",
        "AARON VALDEMAR VAZQUEZ GODINEZ",
        "ABIGAIL LOPEZ",
        "ADRIAN LEYVA",
        "ADRIANA VAZQUEZ",
        "AILEEN MEJIA",
        "ALAN SILVA",
        "ALBERTO FLORES",
        "ALBERTO RODRIGUEZ",
        "ALEJANDRA GALVAN",
        "ALEJANDRINA PARRA",
        "ALEJANDRO JIMENEZ",
        "ALEJANDRO TERREROS",
        "ALEX SANDOVAL",
        "ALEXANDER MARCOS",
        "ALEXEI SANDOVAL",
        "ALMA ANTONIO",
        "ALMA RAMIREZ",
        "ALONDRA BELTRAN",
        "ALONDRA FERNANDEZ",
        "AMOR ALICIA TORRES",
        "ANA CELESTE CASTILLO",
        "ANA GOMEZ",
        "ANA HERNANDEZ",
        "ANA LEON",
        "ANA TOLENTINO",
        "ANA TORRES",
        "ANA URUETA",
        "ANA VALDES",
        "ANDREA TORRES",
        "ANET GASTELO",
        "ANGELICA DIOSELINA LOPEZ NAJERA",
        "ANTONIO GARCIA",
        "ARLIESKYS SICILIA",
        "ASTRID GOMEZ",
        "AXELL SANDOVAL",
        "AZUCENA LUNA",
        "BARBARA ALVAREZ",
        "BEATRIZ JUAREZ",
        "BEATRIZ LOPEZ",
        "BOMFIGLIO SARABIA",
        "BRANDON DELGADO",
        "BRANDON VERDUGO",
        "BRAYAN VILLA",
        "BRENDA PEREZ",
        "BRENDA QUEVEDO",
        "BRENDA RAMOS",
        "BUCIO DOLORES",
        "CARLOS LOPEZ",
        "CARLOS NUÑEZ",
        "CARLOS ORTIZ",
        "CARLOS OSUNA",
        "CARLOS TIRADO",
        "CARLOS VIDAL",
        "CARMINE LENCIONI",
        "CATALINA MALDONADO",
        "CESAR ABRAHAM GONZALEZ GUZMAN",
        "CESAR CAMACHO",
        "CESAR PARTIDA",
        "CHANTAL HERNANDEZ",
        "CINTHYA MERAZ",
        "CLAUDIA AVALOS",
        "CLAUDIA LEYVA",
        "CLAUDIA LUJAN",
        "CLAUDIA NAVARRO",
        "CLAUDINE MARTENS",
        "CRISTIAN TABORA",
        "CRISTINA VACA",
        "CRISTOPHER HERNÁNDEZ",
        "DAMARIS LOPEZ",
        "DAMARIS MAGALY CAÑEDO CABELLOS",
        "DANA GERONIMO",
        "DANIEL VARGAS",
        "DANIELA RAMIREZ",
        "DANILO GONZALEZ",
        "DANNA CARRILLO",
        "DANNA LUCIA BRIZUELA",
        "DARLA BARBA",
        "DAVID PEÑA",
        "DAYANIRA ANAYA",
        "DEBORAH MALDONADO",
        "DEISY TOLENTINO",
        "DELCY ABIGAIL VILLA",
        "DENISSE DE LA TORRE",
        "DENISSE MONTES",
        "DEYANIRA VILLALPANDO",
        "DIANA CASAS",
        "DIANA GALLARDO",
        "DIANNE EQUIHUA",
        "DIEGO MUÑOS",
        "DORA CENTENO",
        "DULCE MONTIEL",
        "EDER ISAAC CEDILLO",
        "EDNA MONTENEGRO",
        "EDUARDO ELISEA",
        "EDUARDO HERNANDEZ",
        "EDUARDO LUNA",
        "EDUARDO VIERA",
        "EFREN CORDERO",
        "ELENA MARTINEZ",
        "ELIM QUIJAS",
        "ELIZABETH ROJAS",
        "EMMA AGUILERA",
        "EMMANUEL MARTINEZ",
        "ENRIQUE ROJAS",
        "ENRIQUE TORRES",
        "ERICK PADILLA",
        "ERICK SANDOVAL",
        "ERIKA CONTRERAS",
        "ERIKA LOPEZ",
        "ERIKA RODRIGUEZ",
        "ESDRAS VILLASONA",
        "ESMERALDA CANIZALES",
        "ESPERANZA LOPEZ",
        "EVELIN GALLEGOS",
        "EVELYN SANCHEZ",
        "FATIMA FERNANDEZ",
        "FERMINA SANCHEZ",
        "FERNANDO JAVIER INZUNZA JUAREZ",
        "FLORENTINA MONTALVO",
        "FRANCISCO VERDUGO",
        "FRIDA MAGAÑA",
        "GABRIELA URIAS",
        "GENESIS DELVAL",
        "GLORIA DANIELA RAMIREZ",
        "GLORIA VELA",
        "GRACIELA BRAVO",
        "GRECIA VAZQUEZ",
        "GRISELDA DOMINGUEZ",
        "GUSTAVO AGUILAR",
        "GUSTAVO DOMINGUEZ",
        "GUSTAVO RAMIREZ",
        "HAZIEL LEWIS",
        "HECTOR LAZARO",
        "HEIDE MURILLO",
        "HERIBERTO GASTELUM",
        "ITZEL MARTINEZ",
        "JAEL AMADOR",
        "JAEN ALVAREZ",
        "JAHEL VAZQUEZ",
        "JAIME MARTINEZ",
        "JANET SERRANO",
        "JANETH MAYA",
        "JANETH SANCHEZ",
        "JASMIN RODRIGUEZ",
        "JAVIER BENITEZ",
        "JAZMIN CARMONA",
        "JAZMIN MARTINEZ",
        "JENIFER LOPEZ BARTOLON",
        "JENIFER LOPEZ MARTINEZ",
        "JENIFER VELAZQUEZ",
        "JESSICA JIMON",
        "JESUS GALINDO",
        "JESUS HERNANDEZ",
        "JESUS MEDINA",
        "JESUS MEZA",
        "JESUS MONTIEL",
        "JESUS MUÑOZ",
        "JESUS RANGEL",
        "JESUS ROJANO",
        "JESUS VILLEGAS",
        "JHOVANA JUAREZ",
        "JOEL OMAR HOLGUIN GARCIA",
        "JOHAN SOTO",
        "JOHANA FIERRO",
        "JONATHAN MORALES",
        "JONATHAN NAVA",
        "JORGE CERVANTES",
        "JORGE GARCIA",
        "JORGE MENDEZ",
        "JORGE SANCHEZ",
        "JORGE SOTELO",
        "JOSE AGUIRRE",
        "JOSE ARELLANO",
        "JOSE ARIAS",
        "JOSE CAMARGO",
        "JOSE EFRAIN REYES",
        "JOSE MARIO ROJAS BENSON",
        "JOSE MEZA",
        "JOSE OROZCO",
        "JOSE REYES",
        "JOSE RIOS",
        "JOSELINE CEDILLO",
        "JOSELYNE LARA",
        "JOSSELIN CHAVEZ",
        "JOVANNY FABIAN",
        "JUAN BUITRON",
        "JUAN COLORADO",
        "JUAN CUNILLAS",
        "JUAN RAMIREZ",
        "JUAN SANTACRUZ",
        "JUAN SANTOS",
        "JUANA GONZALEZ",
        "JULIO LOPEZ",
        "JULIO SOTO",
        "JUPITER LOPEZ",
        "KAREN BRISEÑO",
        "KAREN SALAZAR",
        "KAREN VALDEZ",
        "KARINA TOLENTINO",
        "KARLA CONTRERAS",
        "KARLA GONZALEZ",
        "KARLA SANCHEZ",
        "KARLA SORIANO",
        "KASSANDRA ARAIZA",
        "KATERIN RAMIREZ",
        "KATIA SOTELO",
        "KRISTYAN DIAZ",
        "LAURA MARTINEZ",
        "LAURA SAUCEDO",
        "LAYLA CASTORENA",
        "LEONARDO MEDINA",
        "LESLIE GUEVARA",
        "LESLY LUNA",
        "LESSNY CADENA",
        "LETICIA GUZMAN",
        "LILIANA MARTINEZ",
        "LILIANA RODRIGUEZ",
        "LILIANA SANCHEZ",
        "LITZY HERNANDEZ",
        "LIZBETH ARMENTA",
        "LIZBETH CHUCUAN",
        "LIZBETH LOPEZ",
        "LIZETH BELTRAN",
        "LIZZET LUNA",
        "LLUVIA HERNANDEZ",
        "LOT MORENO",
        "LOURDES GALICIA",
        "LOURDES URUETA",
        "LUIS CONTRERAS",
        "LUIS CRUZ",
        "LUIS ESQUEDA",
        "LUIS HUERTA",
        "LUIS LEAL",
        "LUIS ORTEGA",
        "LUIS ROSALES",
        "LUISA VALADEZ",
        "LUZ CASTILLO",
        "MADISON RAMIREZ",
        "MANUEL LOMELI",
        "MARCELA RIVAS",
        "MARIA AGUILAR",
        "MARIA ARCE",
        "MARIA DE LA CRUZ",
        "MARIA DEL CARMEN FLORES",
        "MARIA REYES",
        "MARIA TRINIDAD",
        "MARIO ALVAREZ",
        "MARIO BERMEJO",
        "MARIO SOTO",
        "MARISOL CENTENO",
        "MARTHA CASTAÑON",
        "MARTHA HIGUERA",
        "MARTHA VALTIERRA",
        "MARTÍN CAMPOS",
        "MELVIN REYES",
        "MERARI HERNANDEZ",
        "MICHELL NAVARRO",
        "MICHELLE GOMEZ",
        "MICHELLE HERRERA",
        "MIGUEL MALDONADO",
        "MIGUEL MARTINEZ",
        "MIGUEL QUEVEDO",
        "MIGUEL RUIZ",
        "MIROSLAVA ROSADO",
        "MOISES DOMINGUEZ",
        "MOISES SARABIA",
        "MONCERATH BRAVO",
        "MONICA CANO",
        "MONICA SIAÑEZ",
        "MONSERRAT LOPEZ",
        "NANCY DEL CARMEN TOLENTINO",
        "NANCY JUAREZ",
        "NATALIE ROMAN",
        "NATALY BAUTISTA",
        "NAYELI DAVALOS",
        "NAYELI DEL MURO",
        "NAYELY SANTIAGO",
        "NAYIRED MAXIMIANO",
        "NIDIA MONTIEL",
        "NIMROT ALVAREZ",
        "NORMA BAUTISTA",
        "OMAR LOPEZ",
        "OSVALDO CASTILLO",
        "PABLO PERAZA",
        "PALOMA SANCHEZ",
        "PAOLA MARTINEZ",
        "PAOLA PATRON",
        "PAOLA SALDAÑA",
        "PAOLA SANCHEZ",
        "PATRICIA ABURTO LINARES",
        "PATRICIA IBARRA",
        "PEDRO BAXIN",
        "PERLA ARAUJO",
        "PERLA GODINEZ",
        "QUIALY COTA",
        "RAUL DUBON",
        "REYNA TAFOYA",
        "RICARDO GARCIA",
        "RICARDO SANCHEZ",
        "RODOLFO GUERRERO",
        "ROSA LOPEZ",
        "ROSALIA ROSALES",
        "RUTH SOLIS",
        "SANDRA CORTES",
        "SANTIAGO RODRIGUEZ",
        "SILVANA MARTINEZ",
        "SILVIA HERNANDEZ",
        "SOFIA GUZMAN",
        "SOLEDAD VITELA",
        "SONIA REYES",
        "STEPHANIE CORTES",
        "STEPHANIE GIL",
        "STEVES CANDELARIO",
        "SUSANA MORENO",
        "TRINIDAD HERNANDEZ",
        "URANI GOMEZ",
        "VALERIA BAILON",
        "VALERIA ESCOBAR",
        "VALERIA GARDUÑO",
        "VALERIA OSUNA",
        "VALERIA VILEGAS",
        "VANESSA PALACIOS",
        "VERONICA VALTIERRA",
        "VICTOR CASTAÑEDA",
        "VICTORIA MALDONADO",
        "VICTORIA MARES",
        "VIRIDIANA ALVAREZ",
        "VIRIDIANA POLO",
        "VIRIDIANA RUBIO",
        "VIVIANA CORTES",
        "WENDY RODRIGUEZ",
        "WILLIAN GARCIA",
        "XIMENA RUBIO",
        "XOCHITL VARGAS",
        "YADIRA PIÑA",
        "YAHAYRA VALDEZ",
        "YAMEL FUENTES",
        "YARELI ROQUE CEBRERO",
        "YARITZA CASTRO",
        "YAZMIN RODRIGUEZ",
        "YESSENIA LEDESMA",
        "YESSENIA LÓPEZ BARRIOS",
        "YESSICA MORENO",
        "ZULEMA CASTAÑEDA",
        "ZULEMA RUIZ",
        "ZULMA RAMIREZ",
    ],
}

export default dataList
